### ISSUE TITLE
demo？

### ISSUE THREAD

**Issue by jinzhenmu** [FuzhiYang/TTSR#1]
Hi, it is a nice work.  is have a demo or test.py?

**Comment by FuzhiYang** [comment]
Currently you can modify codes through "eval.sh", "trainer.py" and so on to test any image pair. We'll update a demo script later.

**Comment by jinzhenmu** [comment]
非常非常非常感谢。


| |
牟金震
邮箱：jinzhen_mu@163.com
|

签名由 网易邮箱大师 定制

On 06/19/2020 23:50, Fuzhi Yang wrote:

Currently you can modify codes through "eval.sh", "trainer.py" and so on to test any image pair. We'll update a demo script later.

**Comment by FuzhiYang** [comment]
Hi Jinzhen, we've already updated a demo script to quick test. You can use that to test any image pairs of lr and ref.

**Comment by jinzhenmu** [comment]
交大的效率太强了！！！ 谢谢
| |
牟金震
|
|
jinzhen_mu@163.com
|
签名由网易邮箱大师定制
On 6/22/2020 11:03，Fuzhi Yang<notifications@github.com> wrote：

Closed #1.
